# Generated by Django 4.2.1 on 2023-05-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameTable",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("created", models.DateTimeField(verbose_name="date created")),
                ("passcode", models.IntegerField()),
                (
                    "chips_to_dollars",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.gametable"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Winning",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("chips", models.IntegerField(default=0)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("created", models.DateTimeField(verbose_name="date created")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.gametable"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(verbose_name="date created")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "from_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_player",
                        to="www.player",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.gametable"
                    ),
                ),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_player",
                        to="www.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyIn",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("created", models.DateTimeField(verbose_name="date created")),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.gametable"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="www.player"
                    ),
                ),
            ],
        ),
    ]
